version: "3"
networks:
    mesh:
    
services:
  front:
    container_name: frontend
    image: ssafy/frontend
    ports:
      - 3000:80
    networks:
      - mesh
      
  backend:
    container_name: backend
    image: ssafy/backend
    ports:
      - 8080:8080
    networks:
      - mesh